### ISSUE TITLE
Project webpage down

### ISSUE THREAD

**Issue by nabijaczleweli** [evemorgen/PlasticMonkeysCansat#35]
http://plastic-monkeys.space, specified both as the project URL as well as the bottom of the README, seems to be down:
![plastic-monkeys.space SS as of 9pm on 23.03.19](https://user-images.githubusercontent.com/6709544/54870997-244a2d00-4dae-11e9-9200-66cb6b2c8c4a.png)

**Comment by evemorgen** [comment]
Thanks for pointing that out, it should be back online again!

**Comment by nabijaczleweli** [comment]
And so it is, magnificent!
